export const LOAD_CUSTOMER_SUCCESS = 'main/LOAD_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_SUCCESS = 'main/UPDATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_SUCCESS = 'main/CREATE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_SUCCESS = 'main/DELETE_CUSTOMER_SUCCESS';
export const CLEAR_ALL_ATTRIBUTES = 'main/CLEAR_ALL_ATTRIBUTES';