export const LOAD_ENTITY_SUCCESS = 'main/LOAD_ENTITY_SUCCESS';
export const UPDATE_ENTITY_SUCCESS = 'main/UPDATE_ENTITY_SUCCESS';
export const CREATE_ENTITY_SUCCESS = 'main/CREATE_ENTITY_SUCCESS';
export const DELETE_ENTITY_SUCCESS = 'main/DELETE_ENTITY_SUCCESS';