export const ADD_ATTRIBUTE_SUCCESS_EDIT = 'edit/ADD_ATTRIBUTE_SUCCESS';
export const UPDATE_ATTRIBUTE_NAME_EDIT = 'edit/UPDATE_ATTRIBUTE_NAME';
export const UPDATE_ATTRIBUTE_TYPE_EDIT = 'edit/UPDATE_ATTRIBUTE_TYPE';
export const DELETE_ATTRIBUTE_EDIT = 'edit/DELETE_ATTRIBUTE';
export const UPDATE_ENTITY_NAME_EDIT = 'edit/UPDATE_ENTITY_NAME';
export const CLEAR_ENTITY_EDIT = 'edit/CLEAR_ENTITY'
export const CLEAR_ALL_ATTRIBUTES_EDIT = 'edit/CLEAR_ALL_ATTRIBUTES'
export const ADD_ATTRIBUTE_SUCCESS_INITIAL_EDIT = 'edit/ADD_ATTRIBUTE_SUCCESS_INITIAL_EDIT'
