export const ADD_ATTRIBUTE_SUCCESS = 'new/ADD_ATTRIBUTE_SUCCESS';
export const UPDATE_ATTRIBUTE_NAME = 'new/UPDATE_ATTRIBUTE_NAME';
export const UPDATE_ATTRIBUTE_TYPE = 'new/UPDATE_ATTRIBUTE_TYPE';
export const DELETE_ATTRIBUTE = 'new/DELETE_ATTRIBUTE';
export const UPDATE_ENTITY_NAME = 'new/UPDATE_ENTITY_NAME';
export const CLEAR_ENTITY = 'new/CLEAR_ENTITY'
export const CLEAR_ALL_ATTRIBUTES = 'new/CLEAR_ALL_ATTRIBUTES'
